### ISSUE TITLE
Improvement on snippets

### ISSUE THREAD

**Issue by octref** [sdras/vue-vscode-snippets#9]
Hey Sarah. Thanks for sharing your snippets by making it an extension and marking Vetur as a dependency.

In the demo, some stuff were not working correctly, so I'm here to ask for your setup and make the right PR to improve the snippets.

1. Vetur offers some `scaffold` snippets, so `vbase` might be unnecessary

![1](https://user-images.githubusercontent.com/4033249/29698123-56ce78ce-8921-11e7-9be3-0731d8c38c9a.gif)

2. I didn't see the snippets showing up in your gif (they should show up like IntelliSense items). **For example, how did you get `vanim` to expand in the `<template>` in your gif?**

Here is how it should be:

![2](https://user-images.githubusercontent.com/4033249/29698206-d2ca07ea-8921-11e7-9154-cc765271fa1f.gif)

3. Vetur divides vue files into "regions" with specific languages, and snippets should be declared according to the regions that they belong to. For example,

```vue
<template>
<!-- vue-html region -->
</template>
<!-- vue region -->
<style lang="scss">
.hi { // scss region
  color: red;  // scss region
}  // scss region
</style>
<!-- vue region -->
```

The idea is, each "region" has a language defined by `lang` value, with the exception of `<template>`, which has language `vue-html`.

Now you are marking everything as js snippets, so they would be available only in `<script>`, which is wrong for `vanim` etc:

![3](https://user-images.githubusercontent.com/4033249/29698454-836dcc52-8923-11e7-8278-87c1bd3b1db9.gif)

The correct way is to divide `template` / `js` snippets into two files, and change the language associations (`template` to `vue-html`, `js` to `javascript`) in your `contributes.snippets` in `package.json`. Top level snippets, such as `vbase` should be associated for language `vue`.

Let me know how you want to proceed. I can soon send a PR that
- removes `vbase` as it's covered by scaffold snippets
- puts snippets into different files and associates them with correct languages

**Comment by sdras** [comment]
Hi Pine!

Thanks for stopping by and reviewing the snippets, and thank you for Vetur. As you probably already guessed, my interest in Vetur as a dependency was not related to the snippets but to the additional support for Vue files, I definitely find it useful and the snippets couldn't work without that, which is an unfortunate side effect of how VS code languages has been set up, so thanks so much for enabling us the ability to use .vue in vscode.

1. That said, I've gotten the most positive feedback for vbase and personally, I find it to be the most useful snippet. As mentioned in the readme, these snippets are less focused around API matching and more around real developer day to day ergonomics. I love using vbase and wouldn't accept a PR to remove it. I understand that you might have something similar in vetur, but in the event that I could one day remove the vetur dependency (this is my hope), I'd like them to stand on their own.

2. The snippets weren't showing up in the intellisense in the original demo due to a syntax error that was corrected a few versions ago. Thanks for watching out, but it's resolved now.

3. If you look back in the PRs, a few people needed the js version of the snippets as well because of the way they worked with JS before importing into Vue files. I allowed for this because, as mentioned before and stated in the readme, the purpose of these snippets are to be useful to common developers for everyday use.

Thanks for alerting me about `vue-html`, I'll likely make a refactor that reflects this, but it does work as it stands currently, in the `vue` json. Or, if you'd like to submit a PR for that (and not the vbase removal), I'd be happy to receive it. If you check out the readme, you can look over the script, html, and other snippets- the documentation separates these tables.

**Comment by sdras** [comment]
This has been open for a few weeks now with no response, so I'm going to close it out. My last comment details what I think next steps could be, but I also don't think they're vital to the project. Thanks!
