### ISSUE TITLE
Remove Vetur from extensionDependencies

### ISSUE THREAD

**Issue by eladcandroid** [sdras/vue-vscode-snippets#92]

**Comment by sdras** [comment]
You need vetur to work with Vue properly in VS Code.

**Comment by eladcandroid** [comment]
@sdras 
We can use other alternatives like these:
https://marketplace.visualstudio.com/items?itemName=znck.vue-language-features&ssr=false#review-details
https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

I don't see how snippets are related to Vetur specific

**Comment by sto3psl** [comment]
@eladcandroid When opening issues it would be nice to describe why you want a specific feature/change. That way maintainers might actually consider helping you.

--- 

Hi @sdras, I'm working on various Vue 3 projects and am using [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) with VSCode instead of Vetur. I read that this is recommended when using `<script setup>` (yes bleeding edge I know 😅) since Vetur doesn't support that yet. The `vue-vscode-snippets` would still be extremely useful for me but Vetur and Volar don't work well together ([Volar readme](https://github.com/johnsoncodehk/volar#note)).
Would you consider removing Vetur as dependency from `vue-vscode-snippets`? Then more people could use it and it shouldn't affect Vetur users.

**Comment by eladcandroid** [comment]
@sto3psl It's really hard to compete with you. Thanks!

**Comment by christhofer** [comment]
Arrive to this issue as well when trying to disable Vetur in order to use Volar.
It's been almost 6 months but Vetur still doesn't support `<script setup>`, so I'd like to try Volar.
But I can't live without this snippets 😄 

I saw this [comment](https://github.com/vuejs/vetur/issues/2296#issuecomment-734345448) referencing to Evan's comment.

Is there a problem if Vetur is excluded from dependency?
