### ISSUE TITLE
vprops modification suggestion

### ISSUE THREAD

**Issue by titusdecali** [sdras/vue-vscode-snippets#97]
This may be personal preference, however when using `vprops` I typically am looking to create a prop that takes a `String` and that prop name is usually `title`.

Perhaps we could streamline things a bit more by changing the default vprops to these.

This isn't exactly generic but will do what snippets are supposed to do, which is help you work faster.

For now, I've just modified this in the snippets folder to cover this need for myself, but this will of course disappear whenever the extension is updated.

**Comment by sdras** [comment]
Totally understand, though props are going to change for everyone. I would say I'm mostly working with Arrays and Objects, someone else may have another need. I'm going to close this out with a note that they are built so that you can easily tab through these options and type rather than needing to go to each field with a mouse, which can also save time. But very supportive of folks personalizing to their own needs!
