### ISSUE TITLE
It will support the Volar

### ISSUE THREAD

**Issue by BWrong** [sdras/vue-vscode-snippets#99]
Now rely on Vetur, It will support the Volar?

**Comment by grmnn** [comment]
For me it worked to just remove the `extensionDependencies` inside the package.json file locally. ( I have both extensions installed but Vetur disabled and Volar enabled)

Just check where your extensions are located. For me on Windows it was in:
`C:\Users\<USER_NAME>\.vscode\extensions\sdras.vue-vscode-snippets-2.2.1`

**Comment by wamich** [comment]
if mac, change file like this ~/.vscode/extensions/sdras.vue-vscode-snippets-2.2.1/package.json.
in the package.json, del the extensionDependencies's content.

**Comment by cheng-shuai** [comment]
Now vetur not support `script setup`  if it will support volar it's a good job!

**Comment by sdras** [comment]
Hey all, thanks for stopping by!

As mentioned above, you can change it in your local settings- I will update the repo's README so that folks can change it if they wish. I don't wish to remove Vetur because I believe it will be too much setup hassle for those just getting started in Vue otherwise, and I want it to be as frictionless as possible. I'm not interested in moving to volar yet, but might change my mind in the future. Thanks again for filing.
